timeout: 120
service:
  externalPort: 3000
  internalPort: 3000
ingress:
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
livenessProbe:
  initialDelaySeconds: 20
  probeType: "exec"
  command:
  - "true"
readinessProbe:
  initialDelaySeconds: 20 
  probeType: "exec"
  command:
  - "true"
application:
  migrateCommand: ["bundle", "exec", "rails", "db:migrate"]
persistence:
  enabled: true
  volumes:
  - name: security-volume
    mount:
      path: /app/security
    claim:
      accessMode: ReadWriteMany
      size: 16M
      storageClass: manual
workers:
  clock:
    replicaCount: "1"
    command: ["bundle", "exec", "clockwork", "config/clock.rb"]
    terminationGracePeriodSeconds:  60
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      probeType: "exec"
      command:
        - "true"
    readinessProbe:
      probeType: "exec"
      command:
        - "true"
  worker:
    replicaCount: "1"
    command: ["bundle", "exec", "rake", "jobs:work"]
    terminationGracePeriodSeconds:  60
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      probeType: "exec"
      command:
        - "true"
    readinessProbe:
      probeType: "exec"
      command:
        - "true"
